392627:Implement Geographical Restrictions on AFD WAF
DEFRA/adp-infrastructure-services pull request #39
Opened 2024-06-19 13:30 UTC by santosh-gh

AB#392627

# **What this PR does / why we need it**:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [x] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [x] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-06-20 10:05 UTC, DaRoszko requested changes

2024-06-20 10:05 UTC, DaRoszko commented on .azuredevops/templates/services-infra-template.yaml
> +              - displayName: 'Process Output Variable'
displayName: Determine WAF Ingress Type

2024-06-20 10:05 UTC, DaRoszko commented on infra/scripts/Set-AFDSecurityPolicy.ps1
> +elseif  ($WafPolicyName -like "*02") {
is this logic here safe? @kbabigumira @ajaysoni-cap

2024-06-20 10:13 UTC, DaRoszko commented on infra/services/adp/ado-callback-api/application-domain.main.bicepparam
> +param ingressType = '#{{ wafPolicyName }}'
It may be wise to ### elaborate on this here.. you could have ingressType & WAF name, to expand upon future design 

@kbabigumira  @ajaysoni-cap  @ppotturi  @santosh-gh

2024-06-20 17:24 UTC, santosh-gh commented on .azuredevops/templates/services-infra-template.yaml
> +              - displayName: 'Process Output Variable'
updated the display name

2024-06-20 17:25 UTC, santosh-gh commented on infra/scripts/Set-AFDSecurityPolicy.ps1
> +elseif  ($WafPolicyName -like "*02") {
removed this

2024-06-21 13:02 UTC, ppotturi submitted a review, later dismissed

2024-06-21 13:34 UTC, rajeshkaremane approved these changes

2024-06-21 13:38 UTC, ajaysoni-cap submitted a review, later dismissed

2024-06-21 14:01 UTC, rajeshkaremane approved these changes

2024-06-21 14:09 UTC, ajaysoni-cap approved these changes

2024-06-21 14:26 UTC, merged